version: '3.1'

services:
  db:
    image: mariadb:10.11.6
    restart: always
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
      - ./sql:/sql
    ports:
      - 3306:3306
